services:

  panorama-whois-KL:
    image: kevinoo/php-laravel-basic-image:php8.3-apache-locales
    container_name: panorama-whois
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8090:80
    environment:
      CONTAINER_ROLE: api
